
name: Build and Deploy Exhibitor Service on Stage
on:
  push:
    branches:
      - github/workflow

jobs:
  build:
    name: push image to registry
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      
      - name: Generate Commit Id
        id: hash-id
        #run: | # echo ${{ github.head_ref }}.${{ github.sha }}
        #run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")"
        run: echo "::set-output name=git_hash::$(git rev-parse --short "$GITHUB_SHA")"
          
    #      git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #      ${{ github.head_ref }}.${{ github.sha }}
         #=$(git rev-parse --short "$GITHUB_SHA")

      # - name: Declare some variables
      #   id: vars
      #   shell: bash
      #   run: |
      #       echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #       echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Build the Docker image
      - name: Package and Build Backend
        run: |
          echo "Building image..."
          sbt docker:publishLocal
      # Tag, and push image to Amazon ECR
      - name: Build, tag
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: billing-service
          IMAGE_TAG: ${{ steps.hash-id.outputs.git_hash }}
        run: |
          echo "Pushing image to ECR..."
          echo $ECR_REPOSITORY
          echo $IMAGE_TAG
          docker tag billing:1.0 $ECR_REPOSITORY:$IMAGE_TAG


  deploy-exhibitor-service-on-eks:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: billing-service
          IMAGE_TAG: ${{ jobs.build.steps.hash-id.outputs.git_hash }}

        run: echo $IMAGE_TAG